spring:
  application:
    name: url-shortener
  datasource:
    url: ${database_url:jdbc:postgresql://localhost:5432/urlshortener}
    username: ${database_username:admin}
    password: ${database_password:admin}